export const filtersType = {
  ALL_TRANSFERS: 'FILTER/ALL_TRANSFERS',
  NO_TRANSFERS: 'FILTER/NO_TRANSFERS',
  ONE_TRANSPLANT: 'FILTER/ONE_TRANSPLANT',
  TWO_TRANSPLANT: 'FILTER/TWO_TRANSPLANT',
  THREE_TRANSPLANT: 'FILTER/THREE_TRANSPLANT',
};
